version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.6.5
        steps:
            - checkout
            - run:
                name: install dependencies
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install .
            - save_cache:
                paths:
                    - ./venv
                key: v1-dependencies-{{ .Branch }}-{{ checksum "setup.py" }}
            - run:
                name: run tests
                command: |
                    . venv/bin/activate
                    tox
            - store_test_results:
                path: test-reports
